### PR TITLE
Moved all go related files to the src folder

### PR DESCRIPTION
**Pull request by ADRFranklin**
~~I also made changes to makefile and travis file for versioning.~~

I thought the path changes would need to be reflected in the makefile and travis, apparently not.

### CODE REVIEW

**Comment by ADRFranklin** [comment]
What do I need to change to fix paths with travis? I'm not familiar with it.

**Comment by Southclaws** [comment]
image

**Comment by Southclaws** [comment]
- https://github.com/Southclaws/sampctl/blob/master/makefile#L3
- https://github.com/Southclaws/sampctl/blob/master/makefile#L27-L32
- https://github.com/Southclaws/sampctl/blob/master/.goreleaser.yml#L18
- https://github.com/Southclaws/sampctl/blob/master/.travis.yml#L22-L23
- https://github.com/Southclaws/sampctl/blob/master/.travis.yml#L28
- https://github.com/Southclaws/sampctl/blob/master/.travis.yml#L33

**Comment by Southclaws** [comment]
Also, main.go must remain in the root of the repository otherwise `go get` installs will break, goreleaser will break, some post-release scripts will break, etc.

https://github.com/Southclaws/sampctl/pull/304/files#diff-79ee049c85e63991a9e8ff435d6d95d4

I will at some point clean this up and improve the release process.

**Pull request closed without merging**
