### PR TITLE
Staging v1.9.0

### PR DESCRIPTION
**Pull request by Southclaws**
This is a staging PR to prepare for v1.9.0

**Note:** When merging this, use `create merge commit` not `squash and merge`.

### CODE REVIEW

**Comment by Southclaws** [comment]
This is probably ready to release soon, unless there are last things you want to get in.

**Comment by ADRFranklin** [comment]
Just a few more things, I want to put in like fixing runtime stuff always being written to the config when it doesn't need to be, and add toml support as a last thing just to finally provide support for it.

**Comment by skyfrk** [comment]
Any update on when this will be merged? As of version `1.8.39` there is a bug where you can not disable usage metrics with an environment variable until a ~/.samp/config.json is created. I would've submitted a PR but I think this PR will remove usage metrics anyway, right?

**Comment by Southclaws** [comment]
Yes, this version removes metrics completely.

**Comment by ADRFranklin** [comment]
Yeah, I'll make a few final changes over the next few days and we can get this merged by the end of the weekend hopefully.

**Pull request merged**
