### PR TITLE
Added file templates.

### PR DESCRIPTION
**Pull request by Alasnkz**
Right now, templates will require to be near the sampctl program path (and to have .pwn or .inc as the extension):

sampctl program path

What/how do I use these templates?
Templates can be used to make a "basic" file that allows you to get coding right away.
Templates modify #define used in the code, no other editing is possible.
An example of a template can be seen below:
sampctl template example

Here's how sampctl asks if you want to edit it:
sampctl template edit

Any issues or bad code (likely) let me know!

### CODE REVIEW

**Comment by Y-Less** [comment]
I'd suggest something more akin to console variables for this.  So `${SERVER_NAME}` not just random defines.

Also: `weed`?

**Comment by BigETI** [comment]
I would prefer having console like variables inside a template script file (what @Y-Less already mentioned), also an optional meta file for each template script file, so the questions can be formatted more user friendly. Also a great addition would be to use environment variables with the `sampctl_` prefix.

Questions should be more like
```
? What should be the name of your server? Test server
? Do you want to use MySQL in your mode? (Y/n) Y
```
instead of
```
? Set SERVER_NAME? Test server
? Set USE_MYSQL? 1
```

**Comment by Alasnkz** [comment]
> I'd suggest something more akin to console variables for this. So `${SERVER_NAME}` not just random defines.

Compromise:

```
#define SERVER_NAME "${CHANGE ME}"
```
(it'll still search the defines but will only ask questions and such if ${xxx} is there.)

> Also: `weed`?

Blaze it.

> also an optional meta file for each template script file, so the questions can be formatted more user friendly

Maybe something like:

```
SERVER_NAME: What would you like to name your server?
USE_MYSQL: Do you want to use MySQL?
```

But then I need to figure out a nice way to allow people to add "default values" to this also.

**Comment by Southclaws** [comment]
I'd like to point out that _package_ templates already exist, though they do solve a _slightly_ different problem to this. `sampctl package template *` is the command.

**Comment by Southclaws** [comment]
I do agree with `${}` syntax though, that would permit changing more than just constants.

**Pull request closed without merging**
