### PR TITLE
enable compiling to Arm architecture

### PR DESCRIPTION
**Pull request by Southclaws**

### CODE REVIEW

**Review by ADRFranklin — APPROVED** [review]

**Comment by ADRFranklin** [comment]
Should this not be merged into development branch instead of master?

**Comment by Southclaws** [comment]
I forgot how this repo works lmao

**Comment by ADRFranklin** [comment]
You might need to fix the fact all of these changes have been made lol

**Comment by Southclaws** [comment]
> You might need to fix the fact all of these changes have been made lol

just needs a rebase because I changed the base branch

**Comment by ADRFranklin** [comment]
@Southclaws When are you going to rebase this?

**Pull request closed without merging**
